import type { KnowledgeRecord } from "./types";

/**
 * Curated STARTER knowledge base (reviewStatus: "unverified").
 *
 * These are paraphrased summaries of well-established public-health guidance,
 * attributed to the authoritative organisation and its stable top-level site.
 * They exist to power and demonstrate the real retrieval + citation engine.
 * Before any production or clinical use, every record must be reviewed against
 * the current primary source by a qualified clinician / medical librarian, its
 * excerpt corrected, its deep-link URL added, and reviewStatus set to
 * "verified". Do not present unverified records as clinically authoritative.
 */
export const KNOWLEDGE_RECORDS: KnowledgeRecord[] = [
  {
    id: "who-activity",
    title: "Physical activity recommendations for adults",
    publisher: "World Health Organization",
    jurisdiction: "global",
    specialty: "primary_care",
    evidenceTier: 1,
    url: "https://www.who.int",
    publishedYear: 2020,
    topics: ["exercise", "activity", "fatigue", "energy", "lifestyle", "prevention"],
    excerpt:
      "Adults should do at least 150–300 minutes of moderate-intensity, or 75–150 minutes of vigorous-intensity, aerobic activity per week, plus muscle-strengthening on 2+ days. Some activity is better than none.",
    reviewStatus: "unverified",
  },
  {
    id: "who-sodium",
    title: "Sodium intake for adults",
    publisher: "World Health Organization",
    jurisdiction: "global",
    specialty: "nutrition",
    evidenceTier: 1,
    url: "https://www.who.int",
    publishedYear: 2023,
    topics: ["sodium", "salt", "blood pressure", "hypertension", "diet", "heart"],
    excerpt:
      "WHO recommends adults consume less than 2000 mg of sodium (about 5 g of salt) per day to reduce blood pressure and cardiovascular risk.",
    reviewStatus: "unverified",
  },
  {
    id: "who-sugar",
    title: "Free sugars intake",
    publisher: "World Health Organization",
    jurisdiction: "global",
    specialty: "nutrition",
    evidenceTier: 1,
    url: "https://www.who.int",
    publishedYear: 2015,
    topics: ["sugar", "added sugar", "diet", "weight", "dental"],
    excerpt:
      "WHO recommends reducing free sugars to less than 10% of total energy intake, with a further reduction to below 5% for additional health benefits.",
    reviewStatus: "unverified",
  },
  {
    id: "cdc-hba1c",
    title: "Diabetes and HbA1c testing",
    publisher: "US Centers for Disease Control and Prevention",
    jurisdiction: "US",
    specialty: "endocrinology",
    evidenceTier: 1,
    url: "https://www.cdc.gov",
    publishedYear: 2024,
    topics: ["diabetes", "hba1c", "blood sugar", "glucose", "prediabetes", "lab"],
    excerpt:
      "An HbA1c of 6.5% or higher indicates diabetes; 5.7–6.4% indicates prediabetes; below 5.7% is typical. Diagnosis should be confirmed with repeat testing and clinical assessment.",
    reviewStatus: "unverified",
  },
  {
    id: "accaha-bp",
    title: "Blood pressure categories (US)",
    publisher: "American College of Cardiology / American Heart Association",
    jurisdiction: "US",
    specialty: "cardiology",
    evidenceTier: 1,
    url: "https://www.heart.org",
    publishedYear: 2017,
    topics: ["blood pressure", "hypertension", "bp", "heart", "cardiac"],
    excerpt:
      "US (ACC/AHA) thresholds: normal <120/80; elevated 120–129/<80; stage 1 hypertension 130–139 or 80–89; stage 2 ≥140 or ≥90 mmHg.",
    reviewStatus: "unverified",
  },
  {
    id: "nice-bp",
    title: "Hypertension diagnosis threshold (UK)",
    publisher: "National Institute for Health and Care Excellence (NICE)",
    jurisdiction: "UK",
    specialty: "cardiology",
    evidenceTier: 1,
    url: "https://www.nice.org.uk",
    publishedYear: 2019,
    topics: ["blood pressure", "hypertension", "bp", "heart", "cardiac"],
    excerpt:
      "NICE (UK) diagnoses hypertension at a clinic blood pressure of 140/90 mmHg or higher, confirmed with ambulatory or home monitoring averaging 135/85 or higher.",
    reviewStatus: "unverified",
  },
  {
    id: "nih-iron",
    title: "Iron and iron-deficiency",
    publisher: "US National Institutes of Health, Office of Dietary Supplements",
    jurisdiction: "US",
    specialty: "hematology",
    evidenceTier: 1,
    url: "https://ods.od.nih.gov",
    publishedYear: 2023,
    topics: ["iron", "anemia", "anaemia", "fatigue", "tired", "energy", "dizzy", "diet"],
    excerpt:
      "Iron deficiency is a common cause of fatigue and can progress to anaemia. Dietary iron comes from meat, poultry, seafood, beans, lentils and fortified grains; vitamin C aids absorption. Diagnosis needs blood tests.",
    reviewStatus: "unverified",
  },
  {
    id: "nih-b12",
    title: "Vitamin B12",
    publisher: "US National Institutes of Health, Office of Dietary Supplements",
    jurisdiction: "US",
    specialty: "nutrition",
    evidenceTier: 1,
    url: "https://ods.od.nih.gov",
    publishedYear: 2024,
    topics: ["b12", "vitamin b12", "fatigue", "tired", "vegetarian", "vegan", "anemia"],
    excerpt:
      "Vitamin B12 deficiency can cause fatigue, weakness and neurological symptoms. People following vegetarian/vegan diets are at higher risk and may need fortified foods or supplements. Confirm with blood testing.",
    reviewStatus: "unverified",
  },
  {
    id: "nih-vitd",
    title: "Vitamin D",
    publisher: "US National Institutes of Health, Office of Dietary Supplements",
    jurisdiction: "US",
    specialty: "nutrition",
    evidenceTier: 1,
    url: "https://ods.od.nih.gov",
    publishedYear: 2024,
    topics: ["vitamin d", "fatigue", "bone", "sunlight", "deficiency", "mood"],
    excerpt:
      "Vitamin D supports bone health; low levels are common. Sources include sunlight, fatty fish and fortified foods. Testing and supplementation should be guided by a clinician.",
    reviewStatus: "unverified",
  },
  {
    id: "usda-protein",
    title: "Protein requirements",
    publisher: "USDA / Dietary Guidelines for Americans",
    jurisdiction: "US",
    specialty: "nutrition",
    evidenceTier: 1,
    url: "https://www.dietaryguidelines.gov",
    publishedYear: 2020,
    topics: ["protein", "muscle", "diet", "macros", "paneer", "dal", "eggs", "gym"],
    excerpt:
      "The Recommended Dietary Allowance for protein is about 0.8 g per kg of body weight per day for average adults; needs are higher for very active people, older adults, and during recovery.",
    reviewStatus: "unverified",
  },
  {
    id: "usda-fiber",
    title: "Dietary fibre",
    publisher: "USDA / Dietary Guidelines for Americans",
    jurisdiction: "US",
    specialty: "nutrition",
    evidenceTier: 1,
    url: "https://www.dietaryguidelines.gov",
    publishedYear: 2020,
    topics: ["fiber", "fibre", "diet", "digestion", "bloating", "vegetables", "whole grain"],
    excerpt:
      "Most adults should aim for roughly 25–38 g of dietary fibre per day from vegetables, fruit, whole grains and legumes. Most people fall short of this.",
    reviewStatus: "unverified",
  },
  {
    id: "cdc-water",
    title: "Water and hydration",
    publisher: "US Centers for Disease Control and Prevention",
    jurisdiction: "US",
    specialty: "primary_care",
    evidenceTier: 1,
    url: "https://www.cdc.gov",
    publishedYear: 2022,
    topics: ["water", "hydration", "dehydration", "fatigue", "headache", "energy"],
    excerpt:
      "Fluid needs vary with body size, activity and climate; there is no single universal target. Dehydration can contribute to fatigue and headache. Thirst and urine colour are practical everyday cues.",
    reviewStatus: "unverified",
  },
  {
    id: "cdc-sleep",
    title: "Sleep recommendations for adults",
    publisher: "US Centers for Disease Control and Prevention",
    jurisdiction: "US",
    specialty: "primary_care",
    evidenceTier: 1,
    url: "https://www.cdc.gov",
    publishedYear: 2022,
    topics: ["sleep", "fatigue", "tired", "energy", "insomnia", "rest"],
    excerpt:
      "Adults generally need 7 or more hours of sleep per night. Persistent poor sleep is a common contributor to daytime fatigue and low energy.",
    reviewStatus: "unverified",
  },
  {
    id: "nhs-headache",
    title: "Headaches — overview and red flags",
    publisher: "UK National Health Service (NHS)",
    jurisdiction: "UK",
    specialty: "neurology",
    evidenceTier: 1,
    url: "https://www.nhs.uk",
    publishedYear: 2023,
    topics: ["headache", "migraine", "head", "pain", "neuro"],
    excerpt:
      "Most headaches are not serious and settle with rest, fluids and simple pain relief. Seek urgent care for a sudden severe ‘worst-ever’ headache, headache with fever and stiff neck, weakness, confusion, or after a head injury.",
    reviewStatus: "unverified",
  },
  {
    id: "nhs-sorethroat",
    title: "Sore throat — self-care and when to seek help",
    publisher: "UK National Health Service (NHS)",
    jurisdiction: "UK",
    specialty: "primary_care",
    evidenceTier: 1,
    url: "https://www.nhs.uk",
    publishedYear: 2023,
    topics: ["sore throat", "throat", "cold", "cough", "fever", "infection"],
    excerpt:
      "Most sore throats are viral and improve within a week with rest, fluids and pain relief. Seek care for difficulty breathing or swallowing, a very high fever, or symptoms that persist or worsen.",
    reviewStatus: "unverified",
  },
  {
    id: "nhs-fever",
    title: "Fever in adults",
    publisher: "UK National Health Service (NHS)",
    jurisdiction: "UK",
    specialty: "primary_care",
    evidenceTier: 1,
    url: "https://www.nhs.uk",
    publishedYear: 2023,
    topics: ["fever", "temperature", "infection", "flu", "chills"],
    excerpt:
      "A fever is usually a sign the body is fighting an infection and often settles with rest and fluids. Seek medical advice for a very high or persistent fever, or if you feel very unwell, breathless, or confused.",
    reviewStatus: "unverified",
  },
  {
    id: "nhs-chestpain",
    title: "Chest pain — when it is an emergency",
    publisher: "UK National Health Service (NHS)",
    jurisdiction: "UK",
    specialty: "emergency_medicine",
    evidenceTier: 1,
    url: "https://www.nhs.uk",
    publishedYear: 2023,
    topics: ["chest pain", "chest", "heart", "cardiac", "emergency", "breathless"],
    excerpt:
      "Sudden chest pain that is heavy or crushing, spreads to the arms/jaw/back, or comes with breathlessness, sweating or nausea can be a heart attack — call emergency services immediately. Do not wait.",
    reviewStatus: "unverified",
  },
  {
    id: "who-bmi",
    title: "Body Mass Index (BMI) categories",
    publisher: "World Health Organization",
    jurisdiction: "global",
    specialty: "primary_care",
    evidenceTier: 1,
    url: "https://www.who.int",
    publishedYear: 2021,
    topics: ["bmi", "weight", "obesity", "overweight", "body mass"],
    excerpt:
      "WHO BMI categories for adults: underweight <18.5; healthy 18.5–24.9; overweight 25–29.9; obesity ≥30. BMI is a population screening tool and does not distinguish muscle from fat or account for all body types.",
    reviewStatus: "unverified",
  },
  {
    id: "cdc-cholesterol",
    title: "Cholesterol overview",
    publisher: "US Centers for Disease Control and Prevention",
    jurisdiction: "US",
    specialty: "cardiology",
    evidenceTier: 1,
    url: "https://www.cdc.gov",
    publishedYear: 2024,
    topics: ["cholesterol", "ldl", "hdl", "lipids", "heart", "lab", "triglycerides"],
    excerpt:
      "High LDL (‘bad’) cholesterol raises cardiovascular risk, while HDL is protective. Interpretation depends on overall risk factors; targets and treatment should be individualised with a clinician.",
    reviewStatus: "unverified",
  },
  {
    id: "nhs-ibs",
    title: "Bloating and IBS",
    publisher: "UK National Health Service (NHS)",
    jurisdiction: "UK",
    specialty: "gastroenterology",
    evidenceTier: 1,
    url: "https://www.nhs.uk",
    publishedYear: 2023,
    topics: ["bloating", "ibs", "stomach", "gut", "digestion", "gas", "bowel"],
    excerpt:
      "Bloating is often related to diet, constipation or irritable bowel syndrome. Fibre, fluids and activity can help. Seek care for persistent change in bowel habit, unexplained weight loss, or blood in stool.",
    reviewStatus: "unverified",
  },
  {
    id: "who-lmm-governance",
    title: "Ethics & governance of large multi-modal models in health",
    publisher: "World Health Organization",
    jurisdiction: "global",
    specialty: "governance",
    evidenceTier: 1,
    url: "https://www.who.int",
    publishedYear: 2024,
    topics: ["ai", "governance", "safety", "ethics", "llm", "policy"],
    excerpt:
      "WHO advises that AI large multi-modal models in health require human oversight, transparency, evidence of safety and effectiveness, and clear communication of limitations before clinical deployment.",
    reviewStatus: "unverified",
  },
];
